
link_config: &link_config
    # total length [km] of heralded connection (i.e. sum of fibers on both sides on midpoint station).
    length_A: 0.0
    # probability that photons are lost when entering connection the connection on either side.
    p_loss_init_A: 0.2
    # attenuation coefficient [dB/km] of fiber on either side.
    p_loss_length_A: 0.25
    # speed of light [km/s] in fiber on either side.
    speed_of_light_A: 200_000
    length_B: 0.0
    p_loss_init_B: 0.2
    p_loss_length_B: 0.25
    speed_of_light_B: 200_000
    # dark-count probability per detection
    dark_count_probability: 0
    # probability that the presence of a photon leads to a detection event
    detector_efficiency: 1.0
    # Hong-Ou-Mandel visibility of photons that are being interfered (measure of photon indistinguishability)
    visibility: 1.0
    # determines whether photon-number-resolving detectors are used for the Bell-state measurement
    num_resolving: False


stacks:
  - name: Node1
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node2
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node3
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null
  - name: Node4
    qdevice_typ: generic
    qdevice_cfg:
      dummy: null


hubs:
  - name: Hub1
    connections:
      - stack: Node1
        distance: 10
      - stack: Node2
        distance: 10
      - stack: Node3
        distance: 5
      - stack: Node4
        distance: 5

    link_typ: heralded-double-click
    link_cfg:
        <<: *link_config

    clink_typ: default
    clink_cfg:
      distance: 0

    schedule_typ: fifo
    schedule_cfg:
      switch_time: 1000
      max_multiplexing: 1

